name: AutoDocX CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint och statisk analys
    runs-on: ubuntu-latest
    steps:
      - name: Check out koden
        uses: actions/checkout@v3
      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installera beroenden
        run: pip install -r requirements.txt
      - name: Kör linting (flake8)
        run: |
          pip install flake8
          flake8 .

  test:
    name: Kör enhetstester
    runs-on: ubuntu-latest
    steps:
      - name: Check out koden
        uses: actions/checkout@v3
      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installera beroenden
        run: pip install -r requirements.txt
      - name: Kör tester med pytest
        run: pytest --maxfail=1 --disable-warnings -q

  generate-docs:
    name: Generera dokumentation
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Check out koden
        uses: actions/checkout@v3
      - name: Installera Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installera beroenden
        run: pip install -r requirements.txt
      - name: Kör AutoDocX
        run: |
          # Kör dokumentationsgenerering med full prompt (exempel)
          python -m src.core.main --path="./" --update --full
      - name: Commit & Push dokumentation
        if: success()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/
          git commit -m "AutoDocX: Uppdaterad dokumentation" || echo "Inga ändringar att committa"
          git push
